=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TableModel.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- The document root. -->

<!ELEMENT table (key-column?,column+)>
  <!-- Defines the full name of a subclass from de.westlb.mgb.client.ui.tablemodel.AbstractPropertyProvider, which implements an appropriate default contructor. --> 
  <!ATTLIST table property-provider-class CDATA #IMPLIED>

<!ELEMENT key-column EMPTY>
  <!ATTLIST key-column property-name CDATA #REQUIRED>


<!ELEMENT column (date-format|number-format|choice-list|file-name-icon|generic-format)?>
  <!ATTLIST column property-name CDATA #REQUIRED>
  <!ATTLIST column header-label CDATA #REQUIRED>
  <!ATTLIST column column-type (default|boolean|number|sicon|icon|currency|date|date_time|float|choice) "default">
  <!ATTLIST column use-property-provider (true|false) "false">

<!ELEMENT date-format EMPTY>
  <!ATTLIST date-format type (time|timelong|date|datelong|datetime|datetimelong) "datetime">

<!ELEMENT number-format EMPTY>
  <!ATTLIST number-format fraction-min-length CDATA "0">
  <!ATTLIST number-format fraction-max-length CDATA "0">
  <!ATTLIST number-format grouping-length CDATA "3">
 
<!-- Defines the full name of a subclass from de.westlb.mgb.client.ui.selection_list.AbstractSelectionList, which implements an appropriate default contructor. --> 
<!ELEMENT choice-list EMPTY>
  <!ATTLIST choice-list list-class CDATA #REQUIRED>

<!-- Defines the full name of a subclass from java.text.Format, which implements an appropriate default contructor. --> 
<!ELEMENT generic-format EMPTY>
  <!ATTLIST generic-format format-class CDATA #REQUIRED>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/UserStatisticTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table property-provider-class="de.westlb.mgb.client.ui.tablemodel.EmployeePropertyProvider">
	<column property-name="userId" header-label="User ID">
	</column>
	<column property-name="userName" header-label="User name">
	</column>
	<column property-name="activeSessionCount" header-label="Active sessions" column-type="number">
	</column>
	<column property-name="sessionCount" header-label="Sessions" column-type="number">
	</column>
	<column property-name="latestSessionCreateTime" header-label="Latest session created">
		<date-format type="time"/>
	</column>
	<column property-name="latestSessionDestroyTime" header-label="Latest session destroyed">
		<date-format type="time"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/build/work/client/classes/de/westlb/mgb/client/ui/tablemodel/TradeTableMoneyMarketShort.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeType" header-label="Trade type">
	</column>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="traderName" header-label="Trader">
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="datelong"/>
	</column>
	<column property-name="systemDate" header-label="System time">
		<date-format type="timelong"/>
	</column>
	<column property-name="maturityDate" header-label="Maturity time">
		<date-format type="datelong"/>
	</column>
	<column property-name="volume" header-label="Volume" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="price" header-label="Price" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TradeTableMoneyMarketLong.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeType" header-label="Trade type">
	</column>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="stornoGroupId" header-label="Trade group">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="traderName" header-label="Trader">
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="reportLocation" header-label="Local Report">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="datelong"/>
	</column>
	<column property-name="systemDate" header-label="System time">
		<date-format type="timelong"/>
	</column>
	<column property-name="maturityDate" header-label="Maturity time">
		<date-format type="datelong"/>
	</column>
	<column property-name="volume" header-label="Volume" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="counterparty" header-label="Counterparty">
	</column>
	<column property-name="tradePrice" header-label="Price" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="currentPriceDifference" header-label="Price difference" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="priceTolerance" header-label="Price tolerance" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="turnover" header-label="Turnover" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="automaticStateCode" header-label="Automatic state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.AutoStateCodeList"/>
	</column>
	<column property-name="manualStateCode" header-label="Manual state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ManualStateCodeList"/>
	</column>
	<column property-name="manualStateComment" header-label="Manual comment">
	</column>
	<column property-name="reclamationStateCode" header-label="Reclamation state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ReclamationStateCodeList"/>
	</column>	
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/HistoryTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table property-provider-class="de.westlb.mgb.client.ui.tablemodel.HistoryPropertyProvider">
	<column property-name="type" header-label="Type">
	</column>
	<column property-name="stateCode" header-label="State code">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.AllStateCodeList"/>
	</column>
	<column property-name="date" header-label="Date">
		<date-format type="time"/>
	</column>
	<column property-name="createdByName" header-label="Created by">
	</column>
	<column property-name="attachmentName" header-label="Attachment" column-type="icon" use-property-provider="true">
	</column>
	<column property-name="comment" header-label="comment">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/PriceDeviationTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="tradeId" header-label="Trade ID">
	</column>
	<column property-name="srcTradeId" header-label="Source Trade ID">
	</column>
	<column property-name="requestId" header-label="Request ID">
	</column>
	<column property-name="requestString" header-label="Request String">
	</column>
	<column property-name="requestDate" header-label="Request Date">
		<date-format type="timelong"/>
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="bookId" header-label="Book">
	</column>
	<column property-name="category" header-label="Category">
	</column>
	<column property-name="summitCategory" header-label="FO Category">
	</column>
	<column property-name="priceCheckCategory" header-label="Price Check Category">
	</column>
	<column property-name="tradePrice" header-label="Trade Price">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="theorericalPrice" header-label="Theorerical Price">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="theorericalDiff" header-label="Theorerical Difference">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="bloombergMinPrice" header-label="Bloomberg Min Price">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="bloombergMaxPrice" header-label="Bloomberg Max Price">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="bloombergDiff" header-label="Bloomberg Difference">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="actualDiff" header-label="Actual Difference">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="tolerance" header-label="Tolerance">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="isNotExceeded" header-label="OK" column-type="boolean">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/TradeTableEquityShort.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="bookId" header-label="Book">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="traderId" header-label="Trader">
	</column>
	<column property-name="systemDate" header-label="System time">
		<date-format type="timelong"/>
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="settlementDate" header-label="Settlement time">
		<date-format type="datelong"/>
	</column>
	<column property-name="price" header-label="Price" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="volume" header-label="Volume" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Web Content/WEB-INF/classes/de/westlb/mgb/client/ui/tablemodel/AddonTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="condition" header-label="Condition">
	</column>
	<column property-name="priceTolerancePercent" header-label="Price tolerance in %">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="timeToleranceMinutes" header-label="Time tolerance in minutes">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="comment" header-label="Comment">
	</column>
	<column property-name="changePending" header-label="Pending change" column-type="boolean">
	</column>
	<column property-name="changeRequestedByName" header-label="Changed by">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TradeTableBondShort.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="isin" header-label="ISIN">
	</column>
	<column property-name="tradeType" header-label="Category">
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="comment" header-label="Alias">
	</column>
	<column property-name="maturityDate" header-label="Maturity date">
		<date-format type="datelong"/>
	</column>
	<column property-name="volume" header-label="Volume" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="price" header-label="Price" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="traderId" header-label="Trader">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="systemDate" header-label="Amend time">
		<date-format type="timelong"/>
	</column>
</table>
