=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TableModel.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- The document root. -->

<!ELEMENT table (key-column?,column+)>
  <!-- Defines the full name of a subclass from de.westlb.mgb.client.ui.tablemodel.AbstractPropertyProvider, which implements an appropriate default contructor. --> 
  <!ATTLIST table property-provider-class CDATA #IMPLIED>

<!ELEMENT key-column EMPTY>
  <!ATTLIST key-column property-name CDATA #REQUIRED>


<!ELEMENT column (date-format|number-format|choice-list|file-name-icon|generic-format)?>
  <!ATTLIST column property-name CDATA #REQUIRED>
  <!ATTLIST column header-label CDATA #REQUIRED>
  <!ATTLIST column column-type (default|boolean|number|sicon|icon|currency|date|date_time|float|choice) "default">
  <!ATTLIST column use-property-provider (true|false) "false">

<!ELEMENT date-format EMPTY>
  <!ATTLIST date-format type (time|timelong|date|datelong|datetime|datetimelong) "datetime">

<!ELEMENT number-format EMPTY>
  <!ATTLIST number-format fraction-min-length CDATA "0">
  <!ATTLIST number-format fraction-max-length CDATA "0">
  <!ATTLIST number-format grouping-length CDATA "3">
 
<!-- Defines the full name of a subclass from de.westlb.mgb.client.ui.selection_list.AbstractSelectionList, which implements an appropriate default contructor. --> 
<!ELEMENT choice-list EMPTY>
  <!ATTLIST choice-list list-class CDATA #REQUIRED>

<!-- Defines the full name of a subclass from java.text.Format, which implements an appropriate default contructor. --> 
<!ELEMENT generic-format EMPTY>
  <!ATTLIST generic-format format-class CDATA #REQUIRED>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/TradeTableBondLong.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="instrumentName" header-label="Instrument">
	</column>
	<column property-name="isin" header-label="ISIN">
	</column>
	<column property-name="tradeCategory" header-label="Category">
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="counterparty" header-label="Counterparty">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="reportLocation" header-label="Local Report">
	</column>
	<column property-name="maturityDate" header-label="Maturity date">
		<date-format type="datelong"/>
	</column>
	<column property-name="volume" header-label="Volume" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="tradePrice" header-label="Price" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="turnover" header-label="Turnover" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="2" grouping-length="3"/>
	</column>
	<column property-name="traderId" header-label="Trader">
	</column>
	<column property-name="updatedBy" header-label="Updated by">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="systemDate" header-label="Amend time">
		<date-format type="timelong"/>
	</column>
	<column property-name="currentPriceDifference" header-label="Price difference" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="priceTolerance" header-label="Price tolerance" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="stornoGroup" header-label="Is Update" column-type="boolean">
	</column>
	<column property-name="automaticStateCode" header-label="Automatic state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.AutoStateCodeList"/>
	</column>
	<column property-name="manualStateCode" header-label="Manual state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ManualStateCodeList"/>
	</column>
	<column property-name="manualStateComment" header-label="Manual comment">
	</column>
	<column property-name="reclamationStateCode" header-label="Reclamation state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ReclamationStateCodeList"/>
	</column>	
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/build/work/client/classes/de/westlb/mgb/client/ui/tablemodel/TradeReclRequiredTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="employeeName" header-label="Employee name">
	</column>
	<column property-name="email" header-label="E-Mail">
	</column>
	<column property-name="phone" header-label="Phone">
	</column>
	<column property-name="manualStateCode" header-label="Manual state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ManualStateCodeList"/>
	</column>
	<column property-name="lateEntry" header-label="Late entry" column-type="boolean">
	</column>
	<column property-name="sourceSystemInstrument" header-label="Instrument">
	</column>
	<column property-name="systemDate" header-label="System time">
		<date-format type="timelong"/>
	</column>
	<column property-name="settlementDate" header-label="Settlement time">
		<date-format type="timelong"/>
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="volume" header-label="Volume" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="price" header-label="Price" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TradeTableRepoLong.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="isin" header-label="ISIN">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="underlyingValueGroup" header-label="Category">
	</column>
	<column property-name="underlyingType" header-label="SubType">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="reportLocation" header-label="Local Report">
	</column>
	<column property-name="volume" header-label="Start cash" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="counterparty" header-label="Counterparty">
	</column>
	<column property-name="repoRate" header-label="Repo rate / Fee / Rate" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="marketPrice" header-label="Repo market price" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="basePointDifference" header-label="BPoint difference" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="basePointTolerance" header-label="BPoint tolerance" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="profitLossEffect" header-label="P/L-effect" column-type="number">
		<number-format fraction-min-length="2" fraction-max-length="2" grouping-length="3"/>
	</column>
	<column property-name="startDate" header-label="Start time">
		<date-format type="datelong"/>
	</column>
	<column property-name="endDate" header-label="End time">
		<date-format type="datelong"/>
	</column>
	<column property-name="automaticStateCode" header-label="Automatic state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.AutoStateCodeList"/>
	</column>
	<column property-name="manualStateCode" header-label="Manual state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ManualStateCodeList"/>
	</column>
	<column property-name="reclamationStateCode" header-label="Reclamation state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ReclamationStateCodeList"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/build/work/client/classes/de/westlb/mgb/client/ui/tablemodel/TradeTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="tradeType" header-label="Category">
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/StornoGroupTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="referenceTradeId" header-label="Reference trade">
	</column>
	<column property-name="fieldName" header-label="Field name">
	</column>
	<column property-name="fieldValue" header-label="Field value">
		<generic-format format-class="de.westlb.mgb.client.ui.util.GeneralFormat"/>
	</column>
	<column property-name="referenceValue" header-label="Reference value">
		<generic-format format-class="de.westlb.mgb.client.ui.util.GeneralFormat"/>
	</column>
	<column property-name="fieldValueChange" header-label="Field value change">
		<generic-format format-class="de.westlb.mgb.client.ui.util.GeneralFormat"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/JobTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table property-provider-class="de.westlb.mgb.client.ui.tablemodel.EmployeePropertyProvider">
	<column property-name="jobId" header-label="Job ID">
	</column>
	<column property-name="systemTime" header-label="Creation time">
		<date-format type="timelong"/>
	</column>
	<column property-name="cob" header-label="Cob">
		<date-format type="date"/>
	</column>
	<column property-name="startBusinessTime" header-label="Start business day">
		<date-format type="timelong"/>
	</column>
	<column property-name="stopBusinessTime" header-label="Stop business day">
		<date-format type="timelong"/>
	</column>
	<column property-name="status" header-label="State">
	</column>
	<column property-name="sourceSystemCode" header-label="Source system">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.SourceSystemList"/>
	</column>
	<column property-name="startLoadTime" header-label="Start load">
		<date-format type="timelong"/>
	</column>
	<column property-name="stopLoadTime" header-label="Stop load">
		<date-format type="timelong"/>
	</column>
	<column property-name="startConvertTime" header-label="Start convert">
		<date-format type="timelong"/>
	</column>
	<column property-name="stopConvertTime" header-label="Stop convert">
		<date-format type="timelong"/>
	</column>
	<column property-name="numberOfTotalRecords" header-label="Total records"  column-type="number">
	</column>
	<column property-name="numberOfLoadErrors" header-label="Load errors"  column-type="number">
	</column>
	<column property-name="numberOfConvertErrors" header-label="Convert errors"  column-type="number">
	</column>
	<column property-name="archived" header-label="Archived" column-type="boolean"/>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TradeTableDerivativeLong.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="stornoGroupId" header-label="Deal">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="structure" header-label="Structure">
	</column>
	<column property-name="tradeType" header-label="Type">
	</column>
	<column property-name="bookId" header-label="Book">
	</column>
	<column property-name="counterparty" header-label="Counterparty">
	</column>
	<column property-name="traderId" header-label="Trader">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="reportLocation" header-label="Local Report">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="systemDate" header-label="Amend time">
		<date-format type="timelong"/>
	</column>
	<column property-name="currentPriceDifference" header-label="Price difference" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="priceTolerance" header-label="Price tolerance" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="tradePrice" header-label="NPV" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="amendmentNpvChange" header-label="NPV Change" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="automaticStateCode" header-label="Automatic state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.AutoStateCodeList"/>
	</column>
	<column property-name="manualStateCode" header-label="Manual state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ManualStateCodeList"/>
	</column>
	<column property-name="manualStateComment" header-label="Manual comment">
	</column>
	<column property-name="reclamationStateCode" header-label="Reclamation state">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.ReclamationStateCodeList"/>
	</column>	
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/AssetTableSWAP.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="assetId" header-label="Asset ID">
	</column>
	<column property-name="tradeSubType" header-label="Sub Type">
	</column>
	<column property-name="callPut" header-label="Call/Put">
	</column>
	<column property-name="payNotional" header-label="Pay Notional" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="payCurrency" header-label="Pay Currency">
	</column>
	<column property-name="payIndexBasis" header-label="Pay Index Basis">
	</column>
	<column property-name="payRateSpread" header-label="Pay Rate Spread" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="5" grouping-length="3"/>
	</column>
	<column property-name="payDiscountCurve" header-label="Pay Discount Curve">
	</column>
	<column property-name="receiveNotional" header-label="Receive Notional" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="receiveCurrency" header-label="Receive Currency">
	</column>
	<column property-name="receiveIndexBasis" header-label="Receive Index Basis">
	</column>
	<column property-name="receiveRateSpread" header-label="Receive Rate Spread" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="5" grouping-length="3"/>
	</column>
	<column property-name="receiveDiscountCurve" header-label="Receive Discount Curve">
	</column>
	<column property-name="capFloor" header-label="Cap/Floor">
	</column>
	<column property-name="buySell" header-label="Buy/Sell">
	</column>
	<column property-name="quantity" header-label="Quantity" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="underlying" header-label="Underlying">
	</column>
	<column property-name="strike" header-label="Strike" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="2" grouping-length="3"/>
	</column>
	<column property-name="style" header-label="Style">
	</column>
	<column property-name="premiumAmount" header-label="Premium Amount" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="premiumCurrency" header-label="Premium Currency">
	</column>
	<column property-name="startDate" header-label="Start date">
		<date-format type="datelong"/>
	</column>
	<column property-name="maturityDate" header-label="Maturity Date">
		<date-format type="datelong"/>
	</column>
	<column property-name="expiryDate" header-label="Expiry Date">
		<date-format type="datelong"/>
	</column>
	<column property-name="fixingDate" header-label="Fixing Date">
		<date-format type="datelong"/>
	</column>
	<column property-name="paymentDate" header-label="Payment Date">
		<date-format type="datelong"/>
	</column>
	<column property-name="firstCouponDate" header-label="First Coupon Date">
		<date-format type="datelong"/>
	</column>
	<column property-name="model" header-label="Model">
	</column>
	<column property-name="instrumentStyle" header-label="Instrument Style">
	</column>
	<column property-name="formula" header-label="Formula">
	</column>
	<column property-name="productName" header-label="Product Name">
	</column>
	<column property-name="prodData" header-label="Prod Data">
	</column>
	<column property-name="npv" header-label="NPV" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="marketRateIR" header-label="Market Rate IR" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="4" grouping-length="3"/>
	</column>
	<column property-name="marketRateVola" header-label="Market Rate Vola" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="2" grouping-length="3"/>
	</column>
	<column property-name="fxRate" header-label="FX Rate" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="4" grouping-length="3"/>
	</column>
	<column property-name="delta" header-label="Delta" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="deltaCurrency" header-label="Delta Currency">
	</column>
	<column property-name="vega" header-label="Vega" column-type="number">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="vegaCurrency" header-label="Vega Currency">
	</column>
</table>
