=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/TableModel.dtd
<?xml version='1.0' encoding='utf-8'?>

<!-- The document root. -->

<!ELEMENT table (key-column?,column+)>
  <!-- Defines the full name of a subclass from de.westlb.mgb.client.ui.tablemodel.AbstractPropertyProvider, which implements an appropriate default contructor. --> 
  <!ATTLIST table property-provider-class CDATA #IMPLIED>

<!ELEMENT key-column EMPTY>
  <!ATTLIST key-column property-name CDATA #REQUIRED>


<!ELEMENT column (date-format|number-format|choice-list|file-name-icon|generic-format)?>
  <!ATTLIST column property-name CDATA #REQUIRED>
  <!ATTLIST column header-label CDATA #REQUIRED>
  <!ATTLIST column column-type (default|boolean|number|sicon|icon|currency|date|date_time|float|choice) "default">
  <!ATTLIST column use-property-provider (true|false) "false">

<!ELEMENT date-format EMPTY>
  <!ATTLIST date-format type (time|timelong|date|datelong|datetime|datetimelong) "datetime">

<!ELEMENT number-format EMPTY>
  <!ATTLIST number-format fraction-min-length CDATA "0">
  <!ATTLIST number-format fraction-max-length CDATA "0">
  <!ATTLIST number-format grouping-length CDATA "3">
 
<!-- Defines the full name of a subclass from de.westlb.mgb.client.ui.selection_list.AbstractSelectionList, which implements an appropriate default contructor. --> 
<!ELEMENT choice-list EMPTY>
  <!ATTLIST choice-list list-class CDATA #REQUIRED>

<!-- Defines the full name of a subclass from java.text.Format, which implements an appropriate default contructor. --> 
<!ELEMENT generic-format EMPTY>
  <!ATTLIST generic-format format-class CDATA #REQUIRED>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Web Content/WEB-INF/classes/de/westlb/mgb/client/ui/tablemodel/TradeTableDerivativeShort.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="isin" header-label="Deal">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="tradeType" header-label="Type">
	</column>
	<column property-name="bookId" header-label="Book">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="traderId" header-label="Trader">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="systemDate" header-label="Amend time">
		<date-format type="timelong"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/StateCodeTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table property-provider-class="de.westlb.mgb.client.ui.tablemodel.StateCodePropertyProvider">
	<column property-name="type" header-label="" column-type="icon" use-property-provider="true">
	</column>
	<column property-name="stateCode" header-label="State code">
	</column>
	<column property-name="shortDescription" header-label="Description">
	</column>
	<column property-name="manualCheckRequired" header-label="Manual check required" column-type="boolean">
	</column>
	<column property-name="reclamationRequired" header-label="Reclamation required" column-type="boolean">
	</column>
	<column property-name="manualSampleCode" header-label="Sample state code" >
	</column>
	<column property-name="manualSamplePercentage" header-label="Sample percentage" >
	</column>
	<column property-name="marketDataRequestType" header-label="Market data request" >
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Web Content/WEB-INF/classes/de/westlb/mgb/client/ui/tablemodel/PriceCheckCategoriesTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="name" header-label="Name">
	</column>
	<column property-name="priceTolerancePercent" header-label="Relative tolerance (in %)">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="priceToleranceAbsolute" header-label="Absolute tolerance">
		<number-format fraction-min-length="2" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="timeToleranceMinutes" header-label="Time tolerance">
		<number-format fraction-min-length="0" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="manualSampleCode" header-label="Sample state code" >
	</column>
	<column property-name="manualSamplePercentage" header-label="Sample percentage" >
	</column>
	<column property-name="changePending" header-label="Pending change" column-type="boolean">
	</column>
	<column property-name="changeRequestedByName" header-label="Changed by">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/ExchangeMappingTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="isin" header-label="ISIN">
	</column>
	<column property-name="sourceSystemCode" header-label="Source system">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.SourceSystemList"/>
	</column>
	<column property-name="isinCountryPrefix" header-label="ISIN country prefix">
	</column>
	<column property-name="sourceSystemExchangeId" header-label="Source system exchange ID">
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="changePending" header-label="Pending change" column-type="boolean">
	</column>
	<column property-name="changeRequestedByName" header-label="Changed by">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Web Content/WEB-INF/classes/de/westlb/mgb/client/ui/tablemodel/BookTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="bookId" header-label="Book ID">
	</column>
	<column property-name="type" header-label="Type">
	</column>
	<column property-name="description" header-label="Description">
	</column>
	<column property-name="businessUnit" header-label="Business unit">
	</column>
	<column property-name="trader" header-label="Trader">
	</column>
	<column property-name="account" header-label="Account" column-type="number">
	</column>
	<column property-name="accountingSystem" header-label="Accounting system">
	</column>
	<column property-name="accountingBranch" header-label="Accounting branch" column-type="number">
	</column>
	<column property-name="costCenter" header-label="Cost center" column-type="number">
	</column>
	<column property-name="limitPosition" header-label="Limit position">
	</column>
	<column property-name="mpireLuName" header-label="mpire LU name">
	</column>
	<column property-name="pcrPlDesk" header-label="PCR PL desk">
	</column>
	<column property-name="pcrPlGroup" header-label="PCR PL group">
	</column>
	<column property-name="foSystem" header-label="FO system">
	</column>
	<column property-name="locationConsolidation" header-label="Location consolidation">
	</column>
	<column property-name="locationGl" header-label="Location GL">
	</column>
	<column property-name="locationPl" header-label="Location PL">
	</column>
	<column property-name="locationTrader" header-label="Location trader">
	</column>
	<column property-name="tradingHead" header-label="Trading head">
	</column>
	<column property-name="tradingBanking" header-label="Trading banking">
	</column>
	<column property-name="tradingType" header-label="Trading type">
	</column>
	<column property-name="wersUnit" header-label="Wers unit" column-type="number">
	</column>
	<column property-name="costCenterName" header-label="Costcenter name">
	</column>
	<column property-name="desk" header-label="Desk">
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/resource/client/de/westlb/mgb/client/ui/tablemodel/DualControlJobTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="entityType" header-label="Type">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.DualControlJobEntityTypeList"/>
	</column>
	<column property-name="entityName" header-label="Name">
	</column>
	<column property-name="operation" header-label="Operation">
		<choice-list list-class="de.westlb.mgb.client.ui.selection_list.DualControlJobOperationList"/>
	</column>
	<column property-name="requestedByName" header-label="Requested by">
	</column>
	<column property-name="requestedDate" header-label="Date">
		<date-format type="time"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Web Content/WEB-INF/classes/de/westlb/mgb/client/ui/tablemodel/TradeTableRepoShort.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<key-column property-name="id"/>
	<column property-name="tradeId" header-label="Trade">
	</column>
	<column property-name="instrument" header-label="Instrument">
	</column>
	<column property-name="tradeType" header-label="Category">
	</column>
	<column property-name="tradeDate" header-label="Trade time">
		<date-format type="timelong"/>
	</column>
	<column property-name="bookId" header-label="Portfolio">
	</column>
	<column property-name="traderLocation" header-label="Location">
	</column>
	<column property-name="price" header-label="Repo rate / Fee / Rate" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="currency" header-label="Currency">
	</column>
	<column property-name="volume" header-label="Notional" column-type="number">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
</table>

=== Dilip96407/Dilip/MGB code/WestLB_RMSC_MGB/Java Source/de/westlb/mgb/client/ui/tablemodel/PriceDeviationStatisticTable.xml
<?xml version="1.0"?>
<!DOCTYPE table SYSTEM "TableModel.dtd">

<table>
	<column property-name="category" header-label="Category">
	</column>
	<column property-name="summitCategory" header-label="SUMMIT Category">
	</column>
	<column property-name="priceCheckCategory" header-label="Price Check Category">
	</column>
	<column property-name="tolerance" header-label="Tolerance">
		<number-format fraction-min-length="4" fraction-max-length="10" grouping-length="3"/>
	</column>
	<column property-name="priceCheckCategoryChangedBy" header-label="Changed By">
	</column>
	<column property-name="priceCheckCategoryChangeDate" header-label="Last Change">
		<date-format type="timelong"/>
	</column>
	<column property-name="numberOfTrades" header-label="Number of Trades">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="numberOfExceededTrades" header-label="Number of Exceeded Trades">
		<number-format fraction-min-length="0" fraction-max-length="0" grouping-length="3"/>
	</column>
	<column property-name="percentageOfExceededTrades" header-label="Exceeded in %">
		<number-format fraction-min-length="2" fraction-max-length="2" grouping-length="3"/>
	</column>
</table>
